name: called
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
  workflow_dispatch:
jobs:
  doathing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |-
          echo {{ github.ref_name }}
